### ISSUE TITLE
Multiple of the same Owned type causes exception with Update-Database

### ISSUE THREAD

**Issue by RedDeathGitHub** [findulov/EntityFrameworkCore.TemporalTables#22]
I want to use multiple of the same type as owned type.
Something like:
```
class Compay {
    public Contact Contact1 { get; set; }
    public Contact Contact2 { get; set; }
}
```

Contact is configured to be owned type, with _.OwnsOne(...)._

When I call _modelBuilder.UseTemporalTables()_ (without this call, it all works)

then during _Update-Database_ I get this exception:

_System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetTableName(IEntityType entityType)
   at EntityFrameworkCore.TemporalTables.Sql.TemporalTableSqlBuilder`1.BuildTemporalTableSqlFromEntityTypeConfiguration(IEntityType entityType, Boolean appendSeparator)
   at EntityFrameworkCore.TemporalTables.Sql.TemporalTableSqlBuilder`1.BuildTemporalTablesSqlForEntityTypes(IEnumerable`1 entityTypes, Boolean appendSeparator)
   at EntityFrameworkCore.TemporalTables.Sql.TemporalTableSqlBuilder`1.BuildTemporalTablesSql(Boolean appendSeparator)
   at EntityFrameworkCore.TemporalTables.Sql.TemporalTableSqlExecutor`1.Execute()
   at EntityFrameworkCore.TemporalTables.Migrations.TemporalTableMigrator`1.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object._

**Comment by RedDeathGitHub** [comment]
Hi @findulov , please have a look!
