### ISSUE TITLE
Migration problems when registering multiple contexts

### ISSUE THREAD

**Issue by itmindsmhc** [findulov/EntityFrameworkCore.TemporalTables#8]
It seems like there is an issue with migrations when registering temporal entities in multiple contexts from different assemblies.
When I try to run a migration on one of the contexts it seems like there is an issue where it tries to migrate an entity that lives in another context here is the command and result:

Update-Database -Context AContext

[17:37:53] [INFO] Entity Framework Core 3.0.0 initialized 'AContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MigrationsAssembly=XXXX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[17:37:54] [INFO] Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
[17:37:54] [INFO] Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
[17:37:54] [INFO] Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
[17:37:54] [INFO] No migrations were applied. The database is already up to date.
[17:37:54] [INFO] Entity Framework Core 3.0.0 initialized 'BContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MigrationsAssembly=XXXXX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetTableName(IEntityType entityType)
   at EntityFrameworkCore.TemporalTables.Sql.TemporalTableSqlBuilder`1.BuildTemporalTableSqlFromEntityTypeConfiguration(IEntityType entityType, Boolean appendSeparator)
   at EntityFrameworkCore.TemporalTables.Sql.TemporalTableSqlBuilder`1.BuildTemporalTablesSqlForEntityTypes(IEnumerable`1 entityTypes, Boolean appendSeparator)
   at EntityFrameworkCore.TemporalTables.Sql.TemporalTableSqlBuilder`1.BuildTemporalTablesSql(Boolean appendSeparator)
   at EntityFrameworkCore.TemporalTables.Sql.TemporalTableSqlExecutor`1.Execute()
   at EntityFrameworkCore.TemporalTables.Migrations.TemporalTableMigrator`1.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

I have setup up both contexts to use internal ServiceProvider, and registered both with:

services.AddEntityFrameworkSqlServer();

services.RegisterTemporalTablesForDatabase<AContext>();

Am I doing something completely wrong or is this a possible issue ?

**Comment by findulov** [comment]
I've migrated the library to use Entity Framework Core 3.1 and I can't seem to reproduce the issue anymore. Can you verify it as well when you have time?

**Comment by itmindsmhc** [comment]
I can’t reproduce it anymore either, must be resolved then. Thanks a lot.
